services:
  app-frontend:
    build:
      dockerfile: ./apps/app-frontend/Dockerfile
      context: .
      target: frontend-dev
    command: pnpm turbo dev --filter app-frontend
    ports:
      - "5321:5321"
    develop:
      watch:
        - action: sync
          path: ./apps/app-frontend/src
          target: /monorepo/apps/app-frontend/src
        - action: sync
          path: ./apps/app-frontend/public
          target: /monorepo/apps/app-frontend/public
        - action: rebuild
          path: ./apps/app-frontend/package.json
          target: /monorepo/apps/app-frontend/package.json

        - action: sync
          path: ./packages/app-shared
          target: /monorepo/packages/app-shared
          ignore:
            - node_modules/
        - action: rebuild
          path: ./packages/app-shared/package.json
          target: /monorepo/packages/app-shared/package.json
    profiles:
      - dev

  app-frontend-prod:
    build:
      dockerfile: ./apps/app-frontend/Dockerfile
      context: .
      target: frontend-prod
    ports:
      - "5321:80"
    profiles:
      - prod
